export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";

export const CREATE_TOUR_REQUEST = "CREATE_TOUR_REQUEST";
export const CREATE_TOUR_SUCCESS = "CREATE_TOUR_SUCCESS";
export const CREATE_TOUR_FAIL = "CREATE_TOUR_FAIL";

export const GET_TOURS_REQUEST = "GET_TOURS_REQUEST";
export const GET_TOURS_SUCCESS = "GET_TOURS_SUCCESS";
export const GET_TOURS_FAIL = "GET_TOURS_FAIL";
