export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";

export const CREATE_TOUR_REQUEST = "CREATE_TOUR_REQUEST";
export const CREATE_TOUR_SUCCESS = "CREATE_TOUR_SUCCESS";
export const CREATE_TOUR_FAIL = "CREATE_TOUR_FAIL";

export const GET_TOURS_REQUEST = "GET_TOURS_REQUEST";
export const GET_TOURS_SUCCESS = "GET_TOURS_SUCCESS";
export const GET_TOURS_FAIL = "GET_TOURS_FAIL";

export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";

export const GET_TOUR_REQUEST = "GET_TOUR_REQUEST";
export const GET_TOUR_SUCCESS = "GET_TOUR_SUCCESS";
export const GET_TOUR_FAIL = "GET_TOUR_FAIL";

export const GET_USER_TOURS_REQUEST = "GET_USER_TOURS_REQUEST";
export const GET_USER_TOURS_SUCCESS = "GET_USER_TOURS_SUCCESS";
export const GET_USER_TOURS_FAIL = "GET_USER_TOURS_FAIL";

export const DELETE_TOUR_REQUEST = "DELETE_TOUR_REQUEST";
export const DELETE_TOUR_SUCCESS = "DELETE_TOUR_SUCCESS";
export const DELETE_TOUR_FAIL = "DELETE_TOUR_FAIL";

export const UPDATE_TOUR_REQUEST = "UPDATE_TOUR_REQUEST";
export const UPDATE_TOUR_SUCCESS = "UPDATE_TOUR_SUCCESS";
export const UPDATE_TOUR_FAIL = "UPDATE_TOUR_FAIL";

export const GET_TOURS_SEARCH_REQUEST = "GET_TOURS_SEARCH_REQUEST";
export const GET_TOURS_SEARCH_SUCCESS = "GET_TOURS_SEARCH_SUCCESS";
export const GET_TOURS_SEARCH_FAIL = "GET_TOURS_SEARCH_FAIL";

export const GET_TOURS_TAG_REQUEST = "GET_TOURS_TAG_REQUEST";
export const GET_TOURS_TAG_SUCCESS = "GET_TOURS_TAG_SUCCESS";
export const GET_TOURS_TAG_FAIL = "GET_TOURS_TAG_FAIL";

export const GET_TOURS_RELATED_REQUEST = "GET_TOURS_RELATED_REQUEST";
export const GET_TOURS_RELATED_SUCCESS = "GET_TOURS_RELATED_SUCCESS";
export const GET_TOURS_RELATED_FAIL = "GET_TOURS_RELATED_FAIL";
